name: Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }} .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}