name: Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  actions: write
  checks: write
  deployments: write
  discussions: write
  id-token: write
  issues: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }} .
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "hello world from ssh"
          debug: true